using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Platform.Common.Storage.Interface;
using Platform.DTOs.Songs;
using Platform.Entities;
using Platform.Interfaces.Songs;

namespace Platform.Services
{
    public class SongService : ISongService
    {
        private readonly ISongRepository _repo;
        private readonly IFileStorageService _storage;
        private readonly IMapper _mapper;

        public SongService(ISongRepository repo, IFileStorageService storage, IMapper mapper)
        {
            _repo = repo;
            _storage = storage;
            _mapper = mapper;
        }

        // Upload a new song    
        public async Task<SongDto> UploadAsync( UploadSongDto dto, int artistId)
        {
            ValidateAudioFile(dto.AudioFile);

            // Extract metadata from the audio file
            var duration = await GetAudioDurationAsync(dto.AudioFile);

            // Upload audio file
            var audioUpload = await _storage.UploadAsync(dto.AudioFile,"songs");

            // Upload cover image if provided
            string? coverImagePath = null;

            if (dto.CoverImage != null)
            {
                var coverUpload = await _storage.UploadAsync( dto.CoverImage, "song-covers");
                coverImagePath = coverUpload.FilePath;
            }

            // Map DTO to  Entity
            var song = _mapper.Map<Song>(dto);

            // Set values generated by the server
            song.Duration = duration;
            song.AudioUrl = audioUpload.FilePath;
            song.CoverImageUrl = coverImagePath;
            song.AudioFormat = Path.GetExtension(dto.AudioFile.FileName).ToLowerInvariant();
            song.ArtistId = artistId;
            song.CreatedAt = DateTime.UtcNow;

            // Save
            var createdSong = await _repo.CreateAsync(song);

            // Map Entity to  DTO
            return _mapper.Map<SongDto>(createdSong);
        }

        // Get all songs uploaded by the authenticated artist   
        public async Task<IEnumerable<SongDto>>GetArtistSongsAsync(int artistId)
        {
            var songs = await _repo.GetArtistSongsAsync(artistId);
            return _mapper.Map<IEnumerable<SongDto>>(songs);
        }

        // Validate the uploaded audio file 
        private static void ValidateAudioFile(IFormFile audioFile)
        {
            if (audioFile == null || audioFile.Length == 0)
            {
                throw new ArgumentException("Audio file is required.");
            }
            var extension = Path.GetExtension(audioFile.FileName).ToLowerInvariant();
            var allowedExtensions =
                new[]
                {".mp3", ".wav"};

            if (!allowedExtensions.Contains(extension))
            {
                throw new ArgumentException("Only MP3 and WAV files are supported.");
            }
        }

        // Get the duration of the audio file using TagLib# 
        private static async Task<TimeSpan>
            GetAudioDurationAsync(IFormFile audioFile)
        {
            var tempFile = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + Path.GetExtension(audioFile.FileName));
            try
            {
                await using (var stream = new FileStream(tempFile, FileMode.Create))
                {
                    await audioFile.CopyToAsync(stream);
                }
                using var file = TagLib.File.Create(tempFile);
                return file.Properties.Duration;
            }
            finally
            {
               if (System.IO.File.Exists(tempFile))
                {
                    System.IO.File.Delete(tempFile);
                }
            }
        }

        // get all song 
        public async Task<IEnumerable<SongDto>> GetSongsAsync()
        {
            var songs = await _repo.GetSongsAsync();
            return _mapper.Map<IEnumerable<SongDto>>(songs);
        }
    }
}